### ISSUE TITLE
No support for different onboarding servers

### ISSUE THREAD

**Issue by timcooijmans** [helium/react-native-helium#31]
The SDK assumes that the onboarding server is the DeWi one; https://github.com/helium/react-native-helium/blob/main/src/Onboarding/onboardingClient.ts#L40

but this is not a valid assumption, the onboarding server should be configurable.

**Comment by cokes518** [comment]
this is fixed:
https://github.com/helium/hotspot-app/pull/1209
https://github.com/helium/maker-starter-app/pull/18
