### ISSUE TITLE
Helium wallet app not supporting location assertions 

### ISSUE THREAD

**Issue by heatedlime** [helium/react-native-helium#86]
The helium wallet app won’t let you re-assert your location. It shows 0 transaction fees, and then says it submitted to blockchain, but nothing happens. 

![IMG_7332](https://github.com/helium/wallet-app/assets/104723888/b21c5db3-cb37-432b-bee0-4c7972b71836)
![IMG_7333](https://github.com/helium/wallet-app/assets/104723888/c6b888c1-da00-4708-9db7-0b2330c9f7db)

**Comment by ChewingGlass** [comment]
This will be fixed in wallet-app version `2.5.6`

**Comment by heatedlime** [comment]
Any idea when that will go live for iOS? And is there any other workaround?

**Comment by Alexxino** [comment]
Same problem here

**Comment by ChewingGlass** [comment]
This should already be live
